# Exported from Render on 2026-02-25T16:45:14Z
version: "1"
projects:
  - name: My project
    environments:
      - name: Production
        services:
          - type: web
            name: Grace
            runtime: python
            repo: https://github.com/AIexpert-ig/Grace
            plan: free
            envVars:
              - key: DATABASE_URL
                sync: false
              - key: TELEGRAM_BOT_TOKEN
                sync: false
              - key: RETELL_SIGNING_SECRET
                sync: false
            region: oregon
            buildCommand: pip install -r requirements.txt
            startCommand: ./start.sh
            autoDeployTrigger: commit
