[tool.poetry]
package-mode = false
name = "grace"
version = "0.1.0"
description = "Grace Telegram Bot"
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.111.0"
uvicorn = "^0.30.0"
sqlalchemy = {extras = ["asyncio"], version = "^2.0.30"}
asyncpg = "^0.29.0"
alembic = "^1.13.1"
python-telegram-bot = "^21.1.1"
pydantic = "^2.7.2"
pydantic-settings = "^2.3.0"
httpx = "^0.27.0"
tenacity = "^8.3.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.2.1"
pytest-asyncio = ">=0.23.5"
pytest-cov = "^5.0.0"
pylint = "^3.2.2"
flake8 = "^7.0.0"
black = "^24.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.pylint.master]
ignore-paths = ["tests"]

[tool.pylint.similarities]
ignore-imports = "yes"
min-similarity-lines = 5